// BillingService.js
// Shared Supabase read/write service layer for the Billing Management module.
//
// MIGRATED FROM FIRESTORE. The big structural change: recordPayment() and
// markBalanceSettled() used to be Firestore runTransaction() calls (folio
// update + payment write + transaction-log write, all atomic). Supabase's
// JS client has no equivalent multi-write transaction primitive, so those
// two now call Postgres RPC functions (record_payment / mark_balance_settled
// — see the SQL migration) that do the same atomic multi-table update
// server-side. Every exported function here keeps its original name and
// camelCase return shape, so none of the 7 screens that import from this
// file needed to change.
//
// folioNumber/receiptNumber generation also simplified: the old
// getNextSequence() counter-transaction dance against a counters/billing
// doc is gone entirely — billing_records.folio_number and
// payments.receipt_number are auto-generated by native Postgres
// sequences (folio_seq/receipt_seq) as column DEFAULTs, so a plain
// INSERT already returns the assigned number.

import { supabase } from '../services/supabase';

// ---------------------------------------------------------------------------
// snake_case (DB) <-> camelCase (app) mapping
// ---------------------------------------------------------------------------

function billingRecordToCamel(row) {
  if (!row) return null;
  return {
    id: row.id,
    folioNumber: row.folio_number,
    reservationRef: row.reservation_id,
    guestUid: row.guest_user_id,
    guestName: row.guest_name,
    roomNumbers: row.room_numbers,
    checkInDate: row.check_in_date,
    checkOutDate: row.check_out_date,
    roomCharges: row.room_charges,
    additionalCharges: row.additional_charges,
    taxServiceCharges: row.tax_service_charges,
    totalAmountDue: row.total_amount_due,
    amountPaid: row.amount_paid,
    remainingBalance: row.remaining_balance,
    billingStatus: row.billing_status,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

function paymentToCamel(row) {
  if (!row) return null;
  return {
    id: row.id,
    folioId: row.folio_id,
    receiptNumber: row.receipt_number,
    reservationRef: row.reservation_id,
    guestName: row.guest_name,
    paymentDate: row.payment_date,
    paymentMethod: row.payment_method,
    amountPaid: row.amount_paid,
    remainingBalanceAfter: row.remaining_balance_after,
    processedByUid: row.processed_by,
    processedByName: row.processed_by_name,
  };
}

function transactionToCamel(row) {
  if (!row) return null;
  return {
    id: row.id,
    timestamp: row.timestamp,
    guestName: row.guest_name,
    reservationRef: row.reservation_id,
    paymentType: row.payment_type,
    amount: row.amount,
    staffUid: row.staff_id,
    staffName: row.staff_name,
    status: row.status,
    note: row.note,
  };
}

// ---------------------------------------------------------------------------
// Billing Records
// ---------------------------------------------------------------------------

/**
 * Creates a guest folio. Called automatically by the check-in flow.
 *
 * If the reservation was paid online (paymentMode: 'online'), the folio
 * is auto-settled immediately after creation via recordPayment(), using
 * the reservation's eWalletProvider as the payment method.
 *
 * paymentMode/eWalletProvider can be passed in directly if the caller
 * already has them; otherwise they're looked up from the reservation row.
 */
export async function createBillingRecord({
  reservationRef,
  guestUid,
  guestName,
  roomNumbers,
  checkInDate,
  checkOutDate,
  roomCharges,
  additionalCharges = 0,
  taxServiceCharges = 0,
  paymentMode,
  eWalletProvider,
}) {
  const totalAmountDue = roomCharges + additionalCharges + taxServiceCharges;

  const { data: inserted, error } = await supabase
    .from('billing_records')
    .insert({
      reservation_id: reservationRef,
      guest_user_id: guestUid || null,
      guest_name: guestName,
      room_numbers: roomNumbers,
      check_in_date: checkInDate,
      check_out_date: checkOutDate,
      room_charges: roomCharges,
      additional_charges: additionalCharges,
      tax_service_charges: taxServiceCharges,
      total_amount_due: totalAmountDue,
      amount_paid: 0,
      remaining_balance: totalAmountDue,
      billing_status: 'unpaid',
    })
    .select('id, folio_number')
    .single();
  if (error) throw error;

  const folioId = inserted.id;

  // Fall back to reading the reservation row if the caller didn't pass
  // payment info explicitly.
  if (paymentMode === undefined && reservationRef) {
    try {
      const { data: resData } = await supabase
        .from('reservations')
        .select('payment_mode, ewallet_provider')
        .eq('id', reservationRef)
        .single();
      if (resData) {
        paymentMode = resData.payment_mode;
        eWalletProvider = resData.ewallet_provider;
      }
    } catch (err) {
      console.error('Could not look up reservation payment info for auto-settlement:', err);
    }
  }

  if (paymentMode === 'online' && totalAmountDue > 0) {
    try {
      await recordPayment({
        folioId,
        amount: totalAmountDue,
        paymentMethod: eWalletProvider || 'online',
        processedByUid: null, // system-generated, no staff member involved
        processedByName: 'Online Payment (Auto)',
      });
    } catch (err) {
      // Don't let an auto-settlement failure block folio creation — the
      // folio still exists as Unpaid and front desk can record payment
      // manually if this fails.
      console.error(`Auto-settlement failed for folio ${folioId}:`, err);
    }
  }

  return { id: folioId, folioNumber: inserted.folio_number };
}

export async function getBillingRecord(folioId) {
  const { data, error } = await supabase
    .from('billing_records')
    .select('*')
    .eq('id', folioId)
    .maybeSingle();
  if (error) throw error;
  return billingRecordToCamel(data);
}

export async function getAllBillingRecords() {
  const { data, error } = await supabase
    .from('billing_records')
    .select('*')
    .order('created_at', { ascending: false });
  if (error) throw error;
  return (data || []).map(billingRecordToCamel);
}

export async function getBillingRecordsByStatus(status) {
  const { data, error } = await supabase
    .from('billing_records')
    .select('*')
    .eq('billing_status', status)
    .order('created_at', { ascending: false });
  if (error) throw error;
  return (data || []).map(billingRecordToCamel);
}

/**
 * Client-side search across folioNumber / guestName / roomNumbers.
 * Kept as an in-memory filter (same approach as the Firestore version) —
 * fine at this property's scale; switch to a Postgres ilike/textSearch
 * query if the guest list grows large enough for this to matter.
 */
export async function searchBillingRecords(searchTerm) {
  const all = await getAllBillingRecords();
  const lower = searchTerm.toLowerCase();
  return all.filter(
    (r) =>
      r.folioNumber?.toLowerCase().includes(lower) ||
      r.guestName?.toLowerCase().includes(lower) ||
      r.roomNumbers?.some((rn) => String(rn).toLowerCase().includes(lower))
  );
}

// ---------------------------------------------------------------------------
// Payments
// ---------------------------------------------------------------------------

/**
 * Records a payment against a folio, updates the folio's running totals
 * and billing status, generates a receipt, and writes a transaction log
 * entry — all atomically via the record_payment() Postgres function, the
 * replacement for the old Firestore runTransaction() block.
 */
export async function recordPayment({
  folioId,
  amount,
  paymentMethod, // "cash" | "gcash" | "card" | "pay_at_hotel"
  processedByUid,
  processedByName,
}) {
  if (amount <= 0) {
    throw new Error('Payment amount must be greater than zero.');
  }

  const { data, error } = await supabase.rpc('record_payment', {
    p_folio_id: folioId,
    p_amount: amount,
    p_payment_method: paymentMethod,
    p_processed_by: processedByUid || null,
    p_processed_by_name: processedByName,
  });
  if (error) throw error;

  return {
    receiptId: data.receiptId,
    receiptNumber: data.receiptNumber,
    transactionId: data.transactionId,
    newAmountPaid: data.newAmountPaid,
    newRemainingBalance: data.newRemainingBalance,
    newStatus: data.newStatus,
  };
}

// ---------------------------------------------------------------------------
// Receipts
// ---------------------------------------------------------------------------

export async function getReceipt(receiptId) {
  const { data, error } = await supabase
    .from('payments')
    .select('*')
    .eq('id', receiptId)
    .maybeSingle();
  if (error) throw error;
  return paymentToCamel(data);
}

export async function getReceiptsForFolio(folioId) {
  const { data, error } = await supabase
    .from('payments')
    .select('*')
    .eq('folio_id', folioId)
    .order('payment_date', { ascending: false });
  if (error) throw error;
  return (data || []).map(paymentToCamel);
}

/**
 * Every receipt across all folios, newest first — powers the top-level
 * "Receipts" sidebar screen (Receiptsscreen.jsx).
 */
export async function getAllReceipts() {
  const { data, error } = await supabase
    .from('payments')
    .select('*')
    .order('payment_date', { ascending: false });
  if (error) throw error;
  return (data || []).map(paymentToCamel);
}

/**
 * Client-side search across receiptNumber / guestName for the Receipts
 * screen's search bar.
 */
export async function searchReceipts(searchTerm) {
  const all = await getAllReceipts();
  const lower = searchTerm.toLowerCase();
  return all.filter(
    (r) =>
      r.receiptNumber?.toLowerCase().includes(lower) ||
      r.guestName?.toLowerCase().includes(lower)
  );
}

// ---------------------------------------------------------------------------
// Outstanding Balances
// ---------------------------------------------------------------------------

export async function getOutstandingBalances() {
  const { data, error } = await supabase
    .from('billing_records')
    .select('*')
    .in('billing_status', ['unpaid', 'partially_paid'])
    .order('updated_at', { ascending: false });
  if (error) throw error;
  return (data || []).map(billingRecordToCamel);
}

/**
 * "Mark as settled" — a front-desk override for edge cases (e.g. waived
 * balance, comp'd stay) rather than a real payment. Writes a transaction
 * entry so it still shows up in the audit trail, tagged distinctly.
 * Atomic via the mark_balance_settled() Postgres function.
 */
export async function markBalanceSettled({ folioId, staffUid, staffName, reason }) {
  const { error } = await supabase.rpc('mark_balance_settled', {
    p_folio_id: folioId,
    p_staff_id: staffUid || null,
    p_staff_name: staffName,
    p_reason: reason || null,
  });
  if (error) throw error;
}

// ---------------------------------------------------------------------------
// Transaction History
// ---------------------------------------------------------------------------

export async function getTransactionHistory({ maxResults = 100 } = {}) {
  const { data, error } = await supabase
    .from('transactions')
    .select('*')
    .order('timestamp', { ascending: false })
    .limit(maxResults);
  if (error) throw error;
  return (data || []).map(transactionToCamel);
}

export async function getTransactionsByDateRange(startDate, endDate) {
  const { data, error } = await supabase
    .from('transactions')
    .select('*')
    .gte('timestamp', startDate)
    .lte('timestamp', endDate)
    .order('timestamp', { ascending: false });
  if (error) throw error;
  return (data || []).map(transactionToCamel);
}

export async function getTransactionsByPaymentMethod(paymentType) {
  const { data, error } = await supabase
    .from('transactions')
    .select('*')
    .eq('payment_type', paymentType)
    .order('timestamp', { ascending: false });
  if (error) throw error;
  return (data || []).map(transactionToCamel);
}

/**
 * Client-side search across guestName / reservationRef for the
 * Transaction History screen's search bar.
 */
export async function searchTransactions(searchTerm) {
  const all = await getTransactionHistory({ maxResults: 500 });
  const lower = searchTerm.toLowerCase();
  return all.filter(
    (t) =>
      t.guestName?.toLowerCase().includes(lower) ||
      t.reservationRef?.toLowerCase().includes(lower)
  );
}